### PR TITLE
Make the args struct generation configurable

### LINKED ISSUE #45: No need for "type args struct" if function takes a single-argument
e.g.

```go
func Test_clonePod(t *testing.T) {
	type args struct {
		pod *corev1.Pod
	}
	tests := []struct {
		name    string
		args    args
		want    *corev1.Pod
		wantErr bool
	}{
	    // TODO: Add test cases.
	}
	...
}
```

In the code above, instead of generating `type args struct { ...}`, it's sufficient to just specify args field in anonymous struct as `*corev1.Pod` and not generate an additional type. This should help create simpler and more readable tests.

### PR DESCRIPTION
**Pull request by jawher**
## Motivation

gotests always generates an `args` struct type to hold the test function/method arguments.

e.g. Given the following function:

```go
func Capitalize(s string) string {
 ...
}
```

gotests will generate the following test:

```go
func TestCapitalize(t *testing.T) {
        type args struct {
                s string
        }
        tests := []struct {
                name string
                args args
                want string
        }{
        // TODO: Add test cases.
        }
        for _, tt := range tests {
                t.Run(tt.name, func(t *testing.T) {
                        if got := Capitalize(tt.args.s); got != tt.want {
                                t.Errorf("Capitalize() = %v, want %v", got, tt.want)
                        }
                })
        }
}
```

## Proposed changes

This PR proposes to make the generation of the `args` struct configurable via a new `-args-struct` flag which accepts one of the following values:

* `always`: The current behaviour. Always generate a `tags` struct
* `never`: never generate a `tags` struct. Instead, embed the arguments directly in the case struct
* `smart`: only generate an `args` struct when the tested function accepts 2 or more arguments. Otherwise embed the single argument in the case struct.

Given the same example function `Capitalize` as above, calling gotests with one of `never` or `smart` values would generate the following test:

```go
func TestCapitalize(t *testing.T) {
        tests := []struct {
                name  string
                s string
                want  string
        }{
        // TODO: Add test cases.
        }
        for _, tt := range tests {
                t.Run(tt.name, func(t *testing.T) {
                        if got := Capitalize(tt.s); got != tt.want {
                                t.Errorf("Capitalize() = %v, want %v", got, tt.want)
                        }
                })
        }
}
```

### Default mode

The default mode is `smart`, which may change the behaviour of gotests.

## Problems

When the arguments are embedded in the case struct, name conflicts may arise, e.g. if a function accepts an argument named `name`, the generated code would not compile as we end up with 2 `name` fields in the same struct:

```go
func TestCapitalize(t *testing.T) {
        tests := []struct {
                name string
                name string
                want string
        }{
        // TODO: Add test cases.
        }
        for _, tt := range tests {
                t.Run(tt.name, func(t *testing.T) {
                        if got := Capitalize(tt.name); got != tt.want {
                                t.Errorf("Capitalize() = %v, want %v", got, tt.want)
                        }
                })
        }
}
```

If this is unacceptable, I can work on this PR some more to handle it.

Fixes #45

### CODE REVIEW

**Comment by cweill** [comment]
@jawher: Thanks for taking the time to put together this pull request. I'm hesitant to merge your request for a couple reasons:

1) As you noticed in the problems section, removing the `args` struct will make it possible to generate tests that don't compile. This was a tough decision to use this struct, since it forces the test author to type more characters to write the test. But it does ensure that all generated tests will compile.

2) I'm not a fan of the `smart` keyword, since it's not clear to me when it should use the args struct versus when it shouldn't. Number of arguments may not be the best parameter. Perhaps naming conflict?

I could be convinced to integrate the `always` and `never` options. `always` should be the default to maintain backwards compatibility. Also it should be clear that choosing the `never` option will allow gotests to generate tests that do not compile.

**Comment by coryb** [comment]
fwiw, I was looking for the `smart` implementation in this PR.  I can imagine that some people might want `smart` to mean **2 or more** or even **3 or more args** before factoring out into an `args` struct.  I wonder if names like `2plus` or `3plus` would be more agreeable instead of `smart` to indicate the desired args struct usage?

As for the naming conflict, perhaps we could prefix the args with `arg` and maybe camel-case so they don't conflict?   Something like:
```
        tests := []struct {
                name string
                argName string
                want string
        }{
```
If you went with some `arg` prefix, I would recommend using it for all arguments, not just those that conflict, so we would also have this from the earlier example:
```
        tests := []struct {
                name string
                argS string
                want string
        }{
```

**Comment by jawher** [comment]
Damn, more than 4 months have passed already 😮 

Sorry for the *hit and run* approach (throw a PR at the repo and flee as fast as you can) 🤣 

@cweill Agreed on both points.

@coryb I like your suggestion, thanks !

Going even further, the `always` and `never` values are just special cases of your suggested threshold approach, where:

* `always` is `1plus`
* `never` is `999plus` for example. If you write functions taking more than `999` arguments, you need to revise some of your life choices 😆 

How about a `-args-struct-threshold` argument which accepts a number, e.g. `-args-struct-threshold=3` ?
The default value would be `1`, meaning generate an ` args` struct for functions taking 1 or more arguments.

Also, +1 to the `arg` prefix.

**Comment by cweill** [comment]
It's good to know that at least two people want this feature. However, I'm hesitant to add another flag that handles a very specific edge case. Because once it's added, it's gonna stay there forever.

Note that PR #61 should make this request moot, since anyone will be able to add whatever smarts templates they want without having to modify/recompile gotests. You can just duplicate the existing function template that gotests uses, and modify it with some basic template knowledge to suit your need. I think it's a very nice solution to this feature request. I could be open to the idea of then having a template repository with a smart argument matching like this.

**Comment by jawher** [comment]
As you mentioned, this PR is now obsolete since #61 was merged 😄

**Pull request closed without merging**
