### PR TITLE
Add GOTESTS_TEMPLATE and GOTESTS_TEMPLATE_DIR environment variables

### LINKED ISSUE #116: Add GOTESTS_TEMPLATE and GOTESTS_TEMPLATE_DIR environment variables
What do you think about adding `GOTESTS_TEMPLATE` and `GOTESTS_TEMPLATE_DIR` environment variables that corresponds to the `-template` and `-template_dir` options?

When working with different projects, some might being using testing framework like https://github.com/stretchr/testify some might not. Having these environment variables available allows users to which between the template types easily especially when using it together with tool like https://github.com/direnv/direnv that can load/unload environment variables depending on the working directory.

Maybe what we can do is allow user to set the `template` or `template_dir` values via both flags and environment variables with the value of the flag takes precedence over the one from environment variables.

I can create a PR if you think this is okay.

### PR DESCRIPTION
**Pull request by shihanng**
Closes #116

### CODE REVIEW

**Comment by shihanng** [comment]
Hi @cweill , is there anything that I can do to improve this PR 🙏 ?

**Comment by cweill** [comment]
@shihanng Please add tests that checks that setting the environment has the intended behavior: 

1. Setting GOTESTS_TEMPLATE will use the template.
2. Setting GOTESTS_TEMPLATE_DIR will use the dir.
3. Setting GOTESTS_TEMPLATE and GOTESTS_TEMPLATE_DIR will use the template over the dir.
4. Setting GOTESTS_TEMPLATE and the flag will prioritize the flag.
5. Setting GOTESTS_TEMPLATE_DIR and the flag will prioritize the flag.

**Comment by shihanng** [comment]
@cweill, thanks for the review. 

The first thing that came to my mind when trying to add test cases is to add them in `/gotests_test.go`. However, I found that it might difficult to do so as the reading from environment variables part is done before `GenerateTests` in `/gotests/main.go`.

I would like to suggest that we test the new `valOrGetenv` function in a new `/gotests/main_test.go`. This should cover the following two cases:

> 4. Setting GOTESTS_TEMPLATE and the flag will prioritize the flag.
> 5. Setting GOTESTS_TEMPLATE_DIR and the flag will prioritize the flag.

Then naturally 

> 1. Setting GOTESTS_TEMPLATE will use the template.

is already covered by existing test cases:

https://github.com/cweill/gotests/blob/62fe1b80bbe2c4c7cb0ab26d868795b47475ab90/gotests_test.go#L638-L645

> 2. Setting GOTESTS_TEMPLATE_DIR will use the dir.
> 3. Setting GOTESTS_TEMPLATE and GOTESTS_TEMPLATE_DIR will use the template over the dir.

are covered by

https://github.com/cweill/gotests/blob/62fe1b80bbe2c4c7cb0ab26d868795b47475ab90/gotests_test.go#L683-L691

What do you think about this proposal?

Note: According to the help message and test case I think 3. should be reversed "will use the dir over the template."

**Comment by cweill** [comment]
@shihanng: This proposal sounds good to me. If you make those changes, I will approve the PR. Thank you.

**Comment by shihanng** [comment]
@cweill , I've added the tests in 18bccc4. Thanks!

**Pull request merged**
