### PR TITLE
Add TemplateData to opts

### LINKED ISSUE #139: Allow loading from externally embedded template data
Currently, there's no way to integrate gotests programmatically with your own binary embedded templates.

Since the current structure doesn't allow for any access to the `tmpls` variable in `internal/render`, and the template functions are also not exported, what I had in mind was doing something similar to how `Template`, `TemplateDir` and `TemplateParams` works.

I'll just create the pull request since I've got something working already.

Tks in advance :+1:

### PR DESCRIPTION
**Pull request by titolins**
Closes #139

### CODE REVIEW

**Comment by titolins** [comment]
@googlebot I signed it!

**Comment by titolins** [comment]
@googlebot I fixed it.

**Comment by titolins** [comment]
@googlebot I fixed it.

**Comment by titolins** [comment]
@googlebot I fixed it.

**Review by cweill — APPROVED** [review]
Looks good to me! Thanks for the contribution @titolins

**Pull request merged**
