### PR TITLE
Adds the test name to the errors

### PR DESCRIPTION
**Pull request by serussell**
Error messages omit the table element name (tt.name), making it difficult (impossible?) to identify which table entry failed.  This patch adds the name to the error message.

### CODE REVIEW

**Comment by serussell** [comment]
I done did sign that there thing.

**Comment by cweill** [comment]
Hi @serussell, I wasn't aware of this issue: the test name should always be printed per test case.

Normally the test name is printed if you are using subtests, and if you are not the test should be printed in the test output. 

Which Go version are you using? Before I can accept your pull request, can you please provide an example of the generated code that is missing the test name?

**Comment by serussell** [comment]
Yes, the pull request may not be the correct solution.  There appears to be an issue using the errors generated by gotest with vim-go (and possibly nvim). When there is only one failure, it does not print all lines of the output and misses the line that contains the test entry line:

With two errors:
```
cmd/leg/main_test.go|39| makeAlias() got1 = 1, want 2
||     --- FAIL: Test_makeAlias/no_sep (0.00s)
cmd/leg/main_test.go|39| makeAlias() got1 = 1, want 0
```

With one:
```
cmd/leg/main_test.go|39| makeAlias() got1 = 1, want 2
```

On the command line, all lines are printed:
```
➜  leg go test .
--- FAIL: Test_makeAlias (0.00s)
    --- FAIL: Test_makeAlias/no_sep (0.00s)
        main_test.go:39: makeAlias() got1 = 1, want 2
FAIL
FAIL    repos.seanrussell.us/legume/cmd/leg     0.002s
```

So `vim-go's` `GoTest()` is stripping out the lines that don't actually reference the error.  By putting the relevant test reference information on a different line, they're getting stripped out. But this isn't an issue with `gotests`, because `GoTest()` is omitting only the last test's lines containing the reference information.

Debugging the interaction between `gotests` and `vim-go` is beyond my immediate ability, so I'll keep my patch local for the moment since it makes generated errors useful for `vim-go`.  You can disregard the patch.

Thanks!

**Comment by cweill** [comment]
Sorry to hear that your bug is in a another castle. It may be worth reporting to the vim-go maintainers if you haven't already.

**Comment by serussell** [comment]
For people encountering the same issue, I filed this ticket; [vim-go#1262](https://github.com/fatih/vim-go/issues/1262).

In summary, vim-go's error parsing regexp is expecting all of the metadata for the report to be on one line, not split across several lines.  The way errors are formatted by go's `testing` package is usually congruent to this regexp, but when used the way gotests uses `testing`, namely `testing.T.Run()`, `testing` does split metadata and the regexp fails to match.

No response yet from the vim-go maintainers, so for the moment executing gotests (and more generally, `testing.T.Run()`) from within vim is unfortunately not an option.

**Pull request closed without merging**
