### PR TITLE
Generate return-parameters with names

### PR DESCRIPTION
**Pull request by msoap**
For example for function:

```go 
func fn1(s1 string) (outStr string, result int, err error) {
	return s1 + s2, 42
}
```
Generate test-function:

```go 
    func TestFn1(t *testing.T) {
    	tests := []struct {
    		name       string
    		s1         string
    		wantOutStr string
    		wantResult int
    		wantErr    bool
    	}{
    	// TODO: Add test cases.
    	}
    	for _, tt := range tests {
    		gotOutStr, gotResult, err := fn1(tt.s1)
    		if (err != nil) != tt.wantErr {
    			t.Errorf("%q. fn1() error = %v, wantErr %v", tt.name, err, tt.wantErr)
    			continue
    		}
    		if gotOutStr != tt.wantOutStr {
    			t.Errorf("%q. fn1() gotOutStr = %v, want %v", tt.name, gotOutStr, tt.wantOutStr)
    		}
    		if gotResult != tt.wantResult {
    			t.Errorf("%q. fn1() gotResult = %v, want %v", tt.name, gotResult, tt.wantResult)
    		}
    	}
    }
```
Sorry, changes in the templates may be not optimal:
internal/render/templates/function.tmpl
internal/render/templates/inline.tmpl

### CODE REVIEW

**Comment by msoap** [comment]
Yes, it is because of `{{Got .}}`

I do not quite understand `text/template`. This variant of `inline.tmpl` dont work :-(
```
{{define "inline"}}{{if .OnlyReturnsOneValue}}{{Got .}} := {{template "call" .}}; {{end}}{{end}}
```

**Comment by cweill** [comment]
LGTM.

**Comment by cweill** [comment]
Turns out it's because the `.` references a different object in the two templates. In one it's a `Function` struct and in the other it's a `Field` struct. `Got` requires a `Field` argument, that's why it didn't work.

**Comment by msoap** [comment]
Thanks, I still think about how to avoid duplication code in template.

**Comment by cweill** [comment]
It's not a big deal. It'll probably be refactored out at some point in the future. 

Thanks for the contribution!

**Pull request merged**
